"""Stage the fitted artifacts the Worker needs, and generate the limitations text.

Everything here is a copy or a rendering of something `scripts/train.py`, `fit_bands.py` and
`fit_genre_gate.py` produced. Nothing is refitted, and nothing is retyped by hand -- the
limitations shown under every verdict are rendered from `artifacts/evaluation.json` for the
reason `api/app.py` gives: an earlier version hard-coded the percentages, the model was
retrained, and the interface went on confidently displaying the previous run's error rates.

    .venv/bin/python edge/scripts/build_artifacts.py [--suffix _remote]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ARTIFACTS = ROOT / "artifacts"
OUT = ROOT / "edge" / "src" / "artifacts.js"

sys.path.insert(0, str(ROOT / "src"))
from palimpsest.limitations import render  # noqa: E402  (import needs sys.path first)


def limitations(suffix: str) -> list[str]:
    """Render the error rates shown under every verdict, from the measurements themselves.

    The rendering lives in `palimpsest.limitations` and is shared with `api/app.py`. It was
    duplicated here once, and the duplicate was the *correct* one: the Python application
    read `evaluation.json` unconditionally while serving whichever detector
    `PALIMPSEST_SUFFIX` selected, so the hosted build and the local build published
    different error rates for the same detector. Rendering both from one function is what
    keeps that fixed rather than fixed-once.

    The repeatability statement is passed in rather than shared, because it is true of this
    deployment only: the Python build scored each essay once and cached the result, so it
    never had to answer the question. Running the observer live does, and a user re-pasting
    the same essay is entitled to know the number moves.
    """
    extra: list[str] = []
    rep_path = ROOT / "edge" / "artifacts" / "repeatability.json"
    if rep_path.exists():
        rep = json.loads(rep_path.read_text(encoding="utf-8"))
        extra.append(
            "Scores are not perfectly repeatable. The observer runs on shared hardware in "
            "reduced precision and does not always return identical numbers for identical "
            f"text: re-running {rep['nDocuments']} essays {rep['runsPerDocument']} times "
            f"each moved a sentence score by up to "
            f"{rep['maxSentenceProbDelta'] * 100:.1f} percentage points and the document "
            f"confidence by up to {rep['maxConfidenceDelta'] * 100:.1f}. The verdict band "
            f"was unchanged in {rep['bandStableDocuments']}/{rep['nDocuments']} cases, but "
            "an essay sitting near a threshold can cross it between runs."
        )
    return render(ARTIFACTS, suffix, extra=extra)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--suffix", default="_remote",
                    help="artifact set to ship; _remote is the configuration docs/ measures")
    args = ap.parse_args()
    s = args.suffix

    def load(name: str, required: bool = True):
        path = ARTIFACTS / f"{name}{s}.json"
        if not path.exists():
            if required:
                raise SystemExit(f"missing {path}")
            return None
        return json.loads(path.read_text(encoding="utf-8"))

    bundle = {
        "suffix": s,
        "detector": load("detector"),
        "documentModel": load("document_detector"),
        "gate": load("genre_gate"),
        "bands": load("bands"),
        "limitations": limitations(s),
        "productReport": json.loads(
            (ARTIFACTS / f"product_report{s}.json").read_text(encoding="utf-8")
        ) if (ARTIFACTS / f"product_report{s}.json").exists() else None,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    # Emitted as a JS module rather than JSON so it imports identically under Node and
    # under workerd. A `.json` import needs an `with { type: "json" }` attribute in one and
    # not the other, and that difference would mean the test and the Worker load the model
    # by different paths.
    OUT.write_text(
        "// Generated by edge/scripts/build_artifacts.py -- do not edit.\n"
        "// Fitted by scripts/train.py, fit_bands.py, fit_genre_gate.py; copied, never refitted.\n"
        f"export default {json.dumps(bundle)};\n",
        encoding="utf-8",
    )
    print(
        f"{OUT.relative_to(ROOT)}  {OUT.stat().st_size / 1024:.1f} KB  "
        f"({len(bundle['detector']['feature_names'])} features, "
        f"flag_threshold={bundle['detector']['flag_threshold']}, "
        f"tMachine={bundle['bands']['tMachine']})"
    )
    for line in bundle["limitations"]:
        print("  -", line[:96] + ("..." if len(line) > 96 else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
