"""Copy `web/` into `edge/assets/` and apply the corrections a public deployment needs.

`web/` stays the single source of the interface. This script is the only thing that writes
`edge/assets/`, and every difference between the two is declared below as a named patch with
a reason. **A patch whose target text is missing aborts the run**, so if the interface is
edited in a way that invalidates a correction, the build fails instead of silently shipping
the old claim -- which is precisely the failure being corrected in the first place.

    .venv/bin/python edge/scripts/sync_web.py
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WEB = ROOT / "web"
ASSETS = ROOT / "edge" / "assets"

BANNER = "<!-- Generated by edge/scripts/sync_web.py from web/. Edit web/, not this file. -->\n"

#: (file, reason, find, replace). Order matters within a file.
PATCHES: list[tuple[str, str, str, str]] = [
    (
        "index.html",
        # This correction used to replace the whole footer, because `web/` claimed the essay
        # never left the machine while `/api/health` reported `textLeavesMachine: true` --
        # the page and the API contradicting each other in one process. That is now fixed at
        # the source: `web/` states the remote case and narrows it from `/api/health` only
        # when the observer really is in-process, so what is left here is the difference
        # between the two deployments rather than a correction of a false claim. A reader of
        # the hosted build has no local process and cannot set an environment variable in
        # one, so the wording addresses a browser, not an operator.
        "privacy statement worded for a public deployment rather than a local process",
        """    observer is a 30-billion-parameter model that is not run in this process. It is not
    stored or logged by this application, but it does leave this machine. To score entirely
    locally, restart with <code>PALIMPSEST_OBSERVER=gpt2</code>.""",
        """    observer is a 30-billion-parameter model that cannot run in your browser. It is not
    stored or logged by this application, but it does leave your machine. To score entirely
    locally, run the project yourself with <code>PALIMPSEST_OBSERVER=gpt2</code>.""",
    ),
    (
        "index.html",
        "surface observer clipping, which silently limits the verdict to the first 6,000 characters",
        """      <span id="status" class="status" role="status" aria-live="polite"></span>
    </div>
  </section>""",
        """      <span id="status" class="status" role="status" aria-live="polite"></span>
    </div>
    <div id="notice" class="notice hidden" role="status"></div>
  </section>""",
    ),
    (
        "app.js",
        "the observer is remote here, so do not tell the user it is local",
        '''  els.status.textContent = "Scoring with the local model…";''',
        '''  els.status.textContent = "Scoring…";''',
    ),
    (
        "app.js",
        "the Worker answers errors as {error, detail}; report rate limits and budget stops plainly",
        """    if (!res.ok) {
      const detail = await res.json().catch(() => ({}));
      throw new Error(detail.detail || `request failed (${res.status})`);
    }""",
        """    if (!res.ok) {
      const body = await res.json().catch(() => ({}));
      throw new Error(body.detail || body.error || `request failed (${res.status})`);
    }""",
    ),
    (
        "app.js",
        "say so when the observer only scored a prefix, rather than presenting a partial verdict as whole",
        """    [els.verdict, els.textPanel, els.limits].forEach((p) => p.classList.remove("hidden"));""",
        """    const notice = document.getElementById("notice");
    if (notice) {
      // The observer scores at most 6,000 characters. Beyond that, sentences carry no
      // observer tokens, are marked unreliable, and are dropped from the document verdict --
      // so the verdict describes a prefix. Presenting that as a verdict on the whole essay
      // would be the same class of quiet overclaim this project exists to avoid.
      if (data.meta && data.meta.clipped) {
        notice.textContent =
          "This essay is longer than the observer scores in one pass (6,000 characters). " +
          "The verdict describes the first 6,000 characters only; the rest is shown " +
          "unhighlighted and was not measured.";
        notice.classList.remove("hidden");
      } else {
        notice.classList.add("hidden");
      }
    }
    [els.verdict, els.textPanel, els.limits].forEach((p) => p.classList.remove("hidden"));""",
    ),
]

EXTRA_CSS = """
/* Added by edge/scripts/sync_web.py -- the hosted build surfaces one extra condition. */
.notice {
  margin-top: 0.75rem;
  padding: 0.6rem 0.8rem;
  border-left: 3px solid #b8860b;
  background: rgba(184, 134, 11, 0.08);
  font-size: 0.9rem;
  line-height: 1.45;
}
.notice.hidden { display: none; }
"""


def main() -> int:
    if not WEB.exists():
        print(f"missing {WEB}", file=sys.stderr)
        return 1

    ASSETS.mkdir(parents=True, exist_ok=True)
    copied = []
    for src in sorted(WEB.iterdir()):
        if src.is_file():
            shutil.copy2(src, ASSETS / src.name)
            copied.append(src.name)

    applied = 0
    for name, reason, find, replace in PATCHES:
        path = ASSETS / name
        if not path.exists():
            print(f"patch target file missing: {name}", file=sys.stderr)
            return 1
        text = path.read_text(encoding="utf-8")
        if find not in text:
            print(
                f"PATCH DID NOT APPLY in {name}: {reason}\n"
                f"  the text it rewrites is no longer present in web/{name}.\n"
                f"  Re-check the correction against the current interface rather than "
                f"deploying without it.",
                file=sys.stderr,
            )
            return 1
        if text.count(find) != 1:
            print(f"patch text is ambiguous in {name} ({text.count(find)} matches): {reason}",
                  file=sys.stderr)
            return 1
        path.write_text(text.replace(find, replace), encoding="utf-8")
        applied += 1

    css = ASSETS / "style.css"
    css.write_text(css.read_text(encoding="utf-8") + EXTRA_CSS, encoding="utf-8")

    html = ASSETS / "index.html"
    html.write_text(BANNER + html.read_text(encoding="utf-8"), encoding="utf-8")

    print(f"edge/assets/: {len(copied)} files from web/ ({', '.join(copied)})")
    print(f"{applied} deployment corrections applied:")
    for name, reason, _, _ in PATCHES:
        print(f"  {name}: {reason}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
