#!/usr/bin/env python
"""Pull essay corpora written by OTHER people's generation pipelines.

    python scripts/fetch_external.py --dataset daigt --per-source 200

Why this exists
---------------
docs/09-frontier-ceiling.md records a supervised classifier that scored AUROC 1.000 on
held-out Claude Opus and turned out to detect nothing: it flagged 0% of real GPT-3.5 essays
from another collection and 17% of real students. It had learned *which pipeline produced a
file*, because every machine essay in this project came from one pipeline -- ours. Provenance
was perfectly confounded with the label, so no internal split could ever have caught it.

That is not a modelling bug and it cannot be fixed by modelling. It is a property of the
corpus, and the only repair is machine text generated by people who are not us.

DAIGT (the Kaggle "LLM - Detect AI Generated Text" community corpus) is the right one for
this project specifically:

  * the domain is STUDENT ESSAYS, on PERSUADE prompts, which is what the product scores.
    RAID and MAGE are larger and better known but are news, wiki, reviews, poetry and code --
    a robustness suite, not a match for this task.
  * the human class is the PERSUADE corpus, i.e. real student writing, not a model's
    impression of it.
  * the machine class was contributed by many different people using many different models
    and prompts -- `llama_70b_v1`, `mistral7binstruct_v2`, `chat_gpt_moth`,
    `llama_falcon_v3_falcon_180b`, `nima_gpt4`, `text-davinci-001`, and others. Every one is
    an independent pipeline.

That last property is the entire point. `meta.pipeline` is preserved on every row so that
evaluation can hold out a whole pipeline, which is the only protocol under which a supervised
number on this task means anything.

How it downloads
----------------
Through HuggingFace's datasets-server REST API, one page of rows at a time, appended straight
to a JSONL file. The full parquet is ~158 MB and the `datasets` library would materialise it
in memory; neither happens here. Nothing is installed, nothing is loaded, and peak memory is
one page of JSON.

Rows are stored grouped by source, so the file is sampled on a STRIDE across its whole length
rather than read from the front -- reading the first N rows would return nothing but the human
class.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import ssl
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

API = "https://datasets-server.huggingface.co/rows"

DATASETS = {
    # name: (hf id, config, split, text field, label field, pipeline field, prompt field)
    "daigt": ("ramensoft/daigt_v3", "default", "train",
              "text", "label", "source", "prompt_name"),
}

PAGE = 100  # datasets-server caps a page at 100 rows
MIN_WORDS = 120


def _ssl_ctx() -> ssl.SSLContext:
    """python.org macOS builds ship without a usable CA bundle; certifi has one."""
    try:
        import certifi

        return ssl.create_default_context(cafile=certifi.where())
    except ImportError:
        return ssl.create_default_context()


def fetch_page(dataset: str, config: str, split: str, offset: int, ctx) -> list[dict]:
    q = urllib.parse.urlencode(
        {"dataset": dataset, "config": config, "split": split,
         "offset": offset, "length": PAGE})
    req = urllib.request.Request(
        f"{API}?{q}", headers={"user-agent": "palimpsest-corpus-fetch/1.0"})
    for attempt in range(4):
        try:
            with urllib.request.urlopen(req, timeout=60, context=ctx) as r:
                return [row["row"] for row in json.loads(r.read().decode("utf-8"))["rows"]]
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError, KeyError) as exc:
            if attempt == 3:
                print(f"  ! offset {offset} failed: {str(exc)[:90]}")
                return []
            time.sleep(2.0 * (attempt + 1))
    return []


def total_rows(dataset: str, ctx) -> int:
    q = urllib.parse.urlencode({"dataset": dataset})
    req = urllib.request.Request(
        f"https://datasets-server.huggingface.co/size?{q}",
        headers={"user-agent": "palimpsest-corpus-fetch/1.0"})
    with urllib.request.urlopen(req, timeout=60, context=ctx) as r:
        return int(json.loads(r.read().decode("utf-8"))["size"]["dataset"]["num_rows"])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dataset", default="daigt", choices=sorted(DATASETS))
    ap.add_argument("--per-source", type=int, default=200,
                    help="cap per pipeline, so one prolific contributor cannot dominate")
    ap.add_argument("--stride-pages", type=int, default=5,
                    help="sample one page every N pages across the whole file")
    args = ap.parse_args()

    hf_id, config, split, f_text, f_label, f_pipe, f_prompt = DATASETS[args.dataset]
    ctx = _ssl_ctx()
    n = total_rows(hf_id, ctx)
    print(f"{hf_id}: {n} rows; sampling every {args.stride_pages} pages of {PAGE}\n")

    per_source: Counter = Counter()
    seen: set[str] = set()
    out_path = ROOT / "data" / "raw" / f"{args.dataset}.jsonl"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    kept = 0

    with out_path.open("w", encoding="utf-8") as fh:
        step = PAGE * args.stride_pages
        for offset in range(0, n, step):
            for row in fetch_page(hf_id, config, split, offset, ctx):
                text = " ".join(str(row.get(f_text) or "").split())
                if len(text.split()) < MIN_WORDS:
                    continue
                pipeline = str(row.get(f_pipe) or "unknown")
                if per_source[pipeline] >= args.per_source:
                    continue
                h = hashlib.sha256(text.encode("utf-8")).hexdigest()
                if h in seen:
                    continue
                seen.add(h)

                machine = int(row.get(f_label) or 0) == 1
                per_source[pipeline] += 1
                fh.write(json.dumps({
                    "id": f"{args.dataset}:{h[:12]}",
                    "source_id": args.dataset,
                    "text": text,
                    "authorship": "machine" if machine else "human",
                    # `pipeline` is the field that makes this corpus worth having: it is what
                    # a leave-one-pipeline-out evaluation holds out.
                    "meta": {"pipeline": pipeline,
                             "prompt": str(row.get(f_prompt) or ""),
                             "dataset": hf_id},
                }, ensure_ascii=False) + "\n")
                kept += 1
            if offset % (step * 20) == 0:
                print(f"  offset {offset:>6d}/{n}  kept {kept}")

    print(f"\n{kept} documents -> {out_path.relative_to(ROOT)}")
    print(f"{'pipeline':44s} {'n':>5s}")
    for p, c in per_source.most_common():
        print(f"  {p:42s} {c:5d}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
